name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Build application
        run: bun run build
        
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
        
      - name: Start server in background
        run: |
          bun run start &
          sleep 10
        env:
          NODE_ENV: production
          
      - name: Wait for server to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:3000/ping; do sleep 1; done'
        
      - name: Run Playwright tests
        run: bunx playwright test
        
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
